from pathlib import Path
p=Path('content/research/notes/open-engineering-specification-article-blueprint.md')
s=p.read_text()

def exact(old,new,label):
    global s
    n=s.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected 1, found {n}')
    s=s.replace(old,new)

exact(
"- after Project viability analysis, an explicit choice: proceed/continue on the Project-selected viable technical basis, issue **specific Bounded Research Authorization** for a Project-defined experiment, reshape/change Organizational assumptions and return to Project, defer, or do not proceed;",
"- when Project viability analysis produces a finding that requires Organizational action, an explicit choice: proceed/continue on the Project-selected viable technical basis, issue **specific Bounded Research Authorization** for a Project-defined experiment that crosses an Organizationally owned boundary, reshape/change Organizational assumptions and return to Project, defer, or do not proceed;",
'organization output qualification')

exact(
"- Project viability conclusion covering Model-Judgment necessity, compared alternatives/candidate category results, technical/control feasibility, Human Authority/fallback/capacity, residual exposure, and complete control economics;",
"- Project viability findings that require Organizational action, carrying the relevant Model-Judgment-necessity/alternative rationale, technical/control feasibility, Human Authority/fallback/capacity, residual exposure, and complete control economics; Project-local technical/category outcomes inside the standing Organizational basis need not be escalated merely because they exist;",
'organization evidence project finding')

exact(
"The upper inputs must remain visually parallel or convergent. Authoritative sources/business intent are the reference basis, external/Organizational change is an independent input, and Project/Runtime material is a lower-level evidence/request stream. None should be drawn as if it is generated by the preceding input. The caption must state that the figure represents a decision horizon and control relationship, not a required department structure or a claim that Organization directly performs downstream technical actions. The same Organizational horizon may act before Project assessment and again after the Project viability conclusion without creating a fifth level.",
"The upper inputs must remain visually parallel or convergent. Authoritative sources/business intent are the reference basis, external/Organizational change is an independent input, and Project findings / Organizationally relevant escalated lower-level material form the evidence/request stream. None should be drawn as if it is generated by the preceding input. The caption must state that the figure represents a decision horizon and control relationship, not a required department structure or a claim that Organization directly performs downstream technical actions. The same Organizational horizon may act before Project assessment and again when a Project finding implicates an Organizationally owned basis or initiative-level decision, without creating a fifth level.",
'figure10 explanatory paragraph')

exact(
"- What viability conclusion must be returned to Organization: Model Judgment unnecessary / deterministic or narrower design preferable; viable as proposed; viable only with narrower scope or changed authority; further bounded research required; technically viable but economically unattractive under current assumptions; or Architectural Veto?",
"- Which result is Project-local, and which Project viability finding requires Organizational action? Project-local results include Model Judgment unnecessary / a deterministic or narrower design preferable when the selected design remains inside the standing Organizational basis. Findings requiring Organizational action include a viable production basis needing Business Authorization; bounded research that crosses an Organizationally owned boundary; technically viable but economically unattractive operation under current assumptions; a required change to an Organizational premise or continuation decision; or Architectural Veto requiring a changed proposal before reassessment.",
'project questions two-route')

p.write_text(s)
