import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { assertFigure3SemanticSource, buildFigure3ControlledObjectSvg } from "./publication-figure3.mjs";
import { assertCurrentArticleFigure3Rendition, renderFigure3 } from "./publication-rendition.mjs";
const root=path.resolve(fileURLToPath(new URL("../..",import.meta.url)));
const semanticSource=readFileSync(path.join(root,"content/research/assets/thinking-systems-figure-3.mmd"),"utf8");
const canonicalFigure3 = `![Figure 3 — The controlled-object shift for the motivating class](../assets/thinking-systems-figure-3.svg)\n\n<!-- Figure 3 editable semantic source: ../assets/thinking-systems-figure-3.mmd -->\n\n**Figure 3 — The controlled-object shift for the motivating class.** Canonical caption.`;
test("Figure 3 publication rendition is a side-by-side motivating-class comparison",()=>{const result=renderFigure3(canonicalFigure3);assert.equal(result.rendered,true);assert.match(result.content,/data-ua-figure3-rendition="side-by-side"/);assert.match(result.content,/data-ua-flow="top-down"/);assert.match(result.content,/Explicitly Authored Software/);assert.match(result.content,/Motivating runtime-judgment class/);assert.doesNotMatch(result.content,/thinking-systems-figure-3\.svg/);assert.match(result.content,/<strong>Figure 3 — The controlled-object shift for the motivating class\.<\/strong>/);});
test("Figure 3 semantic source and deterministic SVG stay coupled",()=>{assert.doesNotThrow(()=>assertFigure3SemanticSource(semanticSource));const svg=buildFigure3ControlledObjectSvg();assert.match(svg,/Explicitly Authored Software/);assert.match(svg,/Motivating runtime-judgment class/);assert.throws(()=>assertFigure3SemanticSource(semanticSource.replace("probabilistic Model Judgment","removed")),/publication comparison requires review/);});
test("current article Figure 3 acceptance preserves one canonical and one rendered figure",()=>{const rendition={figure3Rendition:true,canonicalFigures:[{number:3,panel:null,title:"The controlled-object shift"}],renditionFigures:[{number:3,panel:null,title:"The controlled-object shift"}]};assert.doesNotThrow(()=>assertCurrentArticleFigure3Rendition(rendition));assert.throws(()=>assertCurrentArticleFigure3Rendition({...rendition,figure3Rendition:false}),/side-by-side Figure 3 rendition/);});
