import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
const root=path.resolve(fileURLToPath(new URL("../..",import.meta.url)));
const pub=readFileSync(path.join(root,"content/research/notes/thinking-systems-publication-draft.md"),"utf8");
const man=readFileSync(path.join(root,"content/research/notes/open-engineering-specification-article-draft.md"),"utf8");
const bp=readFileSync(path.join(root,"content/research/notes/open-engineering-specification-article-blueprint.md"),"utf8");
const f3src=readFileSync(path.join(root,"content/research/assets/thinking-systems-figure-3.mmd"),"utf8");
const f3svg=readFileSync(path.join(root,"content/research/assets/thinking-systems-figure-3.svg"),"utf8");
function fig(src,n,title=""){const re=new RegExp("```mermaid\\n((?:(?!```)[\\s\\S])*?)\\n```\\n\\n\\*\\*Figure "+n+" —([^\\n]+)","g");const ms=[...src.matchAll(re)].filter(m=>!title||m[2].includes(title));assert.equal(ms.length,1);return ms[0][1];}
function visibleF3(src){assert.match(src,/!\[Figure 3 — The controlled-object shift for the motivating class\]\(\.\.\/assets\/thinking-systems-figure-3\.svg\)/);assert.match(src,/Figure 3 editable semantic source: \.\.\/assets\/thinking-systems-figure-3\.mmd/);assert.doesNotMatch(src,/```mermaid\n(?:(?!```)[\s\S])*?\n```\n\n\*\*Figure 3 —[^\n]*controlled-object shift/);}
function sourceF3(){assert.match(f3src,/^flowchart LR/m);assert.match(f3src,/subgraph A\["Explicitly Authored Software"\][\s\S]*direction TB/);assert.match(f3src,/subgraph B\["Motivating runtime-judgment class"\][\s\S]*direction TB/);assert.match(f3src,/A1 --> A2 --> A3/);assert.match(f3src,/B1 --> B2 --> B3/);assert.match(f3src,/B1 --> J1 --> B3/);assert.match(f3src,/A2 ~~~ J1/);assert.doesNotMatch(f3src,/ROW3|^block$|columns 2|B1 --> B2 --> J1/);assert.match(f3svg,/viewBox="0 0 1400 690"/);assert.match(f3svg,/Explicitly Authored Software/);assert.match(f3svg,/Motivating runtime-judgment class/);assert.match(f3svg,/x="24" y="62" width="660"/);assert.match(f3svg,/x="716" y="62" width="660"/);}
function ortho(src,n){const m=fig(src,n,"Two orthogonal models");assert.match(m,/^flowchart TB/m);assert.match(m,/subgraph ROW_ORTHO\[" "\][\s\S]*direction LR/);assert.match(m,/subgraph L\["Decision ownership/);assert.match(m,/subgraph F\["Capability functions/);assert.match(m,/subgraph F\["Capability functions — one control architecture, not a sequence"\][\s\S]*direction TB/);assert.match(m,/C\["Controllers \/ decision functions[\s\S]*S\["Sensors and evidence[\s\S]*K\["Constraints and realizations[\s\S]*A\["Actuators and corrective action/);assert.match(m,/C --- S --- K --- A/);assert.doesNotMatch(m,/C\s*-->|S\s*-->|K\s*-->/);assert.match(m,/initial admissibility \+ assessment eligibility/);assert.match(m,/specific Bounded Research Authorization/);assert.match(m,/Business Authorization or changed basis/);assert.match(m,/applicable Project Authorization scope \/ set/);assert.match(m,/research-only and\/or production-capable/);assert.match(m,/realization \/ experiment evidence/);assert.match(m,/risk \/ feasibility \/ Model Judgment necessity/);assert.match(m,/Exogenous Organizational change/);assert.doesNotMatch(m,/classDef railpoint|\bJ2\b|\bJ3\b|\bJ4\b|CAP_TOP|CAP_BOTTOM/);}
test("Figure 3 papers use one deterministic SVG rendition",()=>{visibleF3(pub);visibleF3(man);sourceF3();});
test("orthogonal model stays as two side-by-side panels",()=>{ortho(pub,8);ortho(man,9);});
test("blueprint owns the structural layout contract",()=>{assert.match(bp,/versioned deterministic SVG as the visible Markdown and publication rendition/);assert.match(bp,/thinking-systems-figure-3\.mmd/);assert.match(bp,/Visual Review v3/);assert.match(bp,/geometry change requires explicit visual review/);assert.match(bp,/`ROW_ORTHO` subgraph with `direction LR`/);assert.match(bp,/Controllers → Sensors → Constraints → Actuators/);assert.match(bp,/plain non-directional Mermaid links \(`---`\)/);});
